.PHONY: clean All

All:
	@echo "==========Building project:[ 1FirstProgram - Debug ]=========="
	@cd "1FirstProgram" && "$(MAKE)" -f  "1FirstProgram.mk"
clean:
	@echo "==========Cleaning project:[ 1FirstProgram - Debug ]----------"
	@cd "1FirstProgram" && "$(MAKE)" -f  "1FirstProgram.mk" clean
