.PHONY: clean All

All:
	@echo "==========Building project:[ 4IO - Debug ]=========="
	@cd "4IO\4IO" && "$(MAKE)" -f  "4IO.mk"
clean:
	@echo "==========Cleaning project:[ 4IO - Debug ]----------"
	@cd "4IO\4IO" && "$(MAKE)" -f  "4IO.mk" clean
